
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1000,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EASY = new javax.swing.JButton();
        MODERATE = new javax.swing.JButton();
        DIFFICULT = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        EASY.setBackground(new java.awt.Color(181, 229, 120));
        EASY.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        EASY.setText("EASY");
        EASY.setBorder(null);
        EASY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EASYActionPerformed(evt);
            }
        });
        jPanel1.add(EASY);
        EASY.setBounds(271, 121, 500, 50);

        MODERATE.setBackground(new java.awt.Color(181, 229, 120));
        MODERATE.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        MODERATE.setText("MODERATE");
        MODERATE.setBorder(null);
        MODERATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODERATEActionPerformed(evt);
            }
        });
        jPanel1.add(MODERATE);
        MODERATE.setBounds(271, 261, 500, 50);

        DIFFICULT.setBackground(new java.awt.Color(181, 229, 120));
        DIFFICULT.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        DIFFICULT.setText("DIFFICULT");
        DIFFICULT.setBorder(null);
        DIFFICULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIFFICULTActionPerformed(evt);
            }
        });
        jPanel1.add(DIFFICULT);
        DIFFICULT.setBounds(271, 401, 500, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 618, 0, 0);

        jButton2.setBackground(new java.awt.Color(121, 173, 182));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HARD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 410, 420, 90);

        jButton3.setBackground(new java.awt.Color(121, 173, 182));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EASY");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 87, 420, 90);

        jButton4.setBackground(new java.awt.Color(121, 173, 182));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MODERATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 250, 420, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trixie\\OneDrive\\Documents\\easy etc etec.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EASYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EASYActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_EASYActionPerformed

    private void MODERATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODERATEActionPerformed
        // TODO add your handling code here:
        ModerateLevel jfmoderate = new ModerateLevel();
        jfmoderate.show();
        
        dispose();
    }//GEN-LAST:event_MODERATEActionPerformed

    private void DIFFICULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIFFICULTActionPerformed
        // TODO add your handling code here:
        hard jfhard = new hard();
        jfhard.show();
        
        dispose();
    }//GEN-LAST:event_DIFFICULTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        EasyLevel jfeasy = new EasyLevel();
        jfeasy.show();
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         ModerateLevel jfmoderate = new ModerateLevel();
        jfmoderate.show();
        
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hard jfhard = new hard();
        jfhard.show();
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton DIFFICULT;
    public javax.swing.JButton EASY;
    public javax.swing.JButton MODERATE;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
